# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb1877cdbe1ecd98f95f37f4aa17246bbc688af6044d50a2b420e9eb664c114a4427f2040a60cbef1a4f94f9d7497b0eb261e6b09b77194945815e093579158

test:
  secret_key_base: c368156edb9d095217f1965183727cfc199a3fd47d2fdf910d0ca49166102a61806cccd0a5a8c8a570158ae0cf4799b9900c279da968a5a3a165e2f0f505d344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
